Refactoring
SergeBrakow/neuefische-capstone-project-Cibri pull request #22
Opened 2022-11-21 10:51 UTC by SergeBrakow

a necessary restructuring of the code. So that triggered functionalities can work

2022-11-21 15:06 UTC, Kheirah requested changes

2022-11-22 10:18 UTC, SergeBrakow commented on src/components/CustomerViewSection.js
> +            ordersTheCustomerIsLinked.push(order): ""
fixed

2022-11-22 10:18 UTC, SergeBrakow commented on src/components/CustomerViewSection.js
> +const Name = styled.p`
fixed

2022-11-22 10:19 UTC, SergeBrakow commented on src/components/NeedLoginMessage.js
> +      </fieldset>
fixed

2022-11-22 10:19 UTC, SergeBrakow commented on src/components/UserViewSection.js
> +                                checked={right.value === true ? true: false}
fixed

2022-11-22 10:19 UTC, SergeBrakow commented on src/pages/ErrorPage.js
> +        <h1>Cibr2i</h1>
fixed

2022-11-22 10:19 UTC, SergeBrakow commented on src/utils/localStorage.js
> +            name: "crateOrder",
done

2022-11-22 15:44 UTC, SergeBrakow commented on src/components/UserLinkedInOrderSection.js
> +    }
fixed

2022-11-22 19:11 UTC, merged